USE sql_store;

-- SET ISOLATION LEVEL TO REPEATABLE READ, WILL READ THE FIRST VALUE ALWAYS WHERE BEEN COMMITTED OR NOT.
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

START TRANSACTION;


-- REPEATABLE READ ISOLATION LEVEL WILL ENSURE CONSISTENCY FOR ALL QUERIES
SELECT points FROM customers WHERE customer_id = 1;
SELECT points FROM customers WHERE customer_id = 1;

COMMIT;
