CREATE DATABASE IF NOT EXISTS sql_store2;

USE sql_store2;

DROP TABLE IF EXISTS Customers;
CREATE TABLE IF NOT EXISTS Customers
(
	customer_id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    points INTEGER NOT NULL DEFAULT 0,
    email VARCHAR(255) NOT NULL UNIQUE
);