USE SQL_INVOICING;

SELECT P.PAYMENT_ID ,C.NAME ,C.ADDRESS , P.AMOUNT,PM.NAME  
FROM PAYMENTS P
JOIN CLIENTS C
	ON P.CLIENT_ID  = C.CLIENT_ID 
JOIN PAYMENT_METHODS PM
	ON P.PAYMENT_METHOD = PM.PAYMENT_METHOD_ID 